Fixed: Abort `execve()` with a debug error if `argv[0]` length is `>= 128` on Android `< 6` instead of letting process fail post `execve()` without an error
For Android `< 6`, the length must not be `>= 128` for the `argv[0]` string of an `execve()` call or library path of a `dlopen()` call.

The `soinfo_alloc()` function in `linker.cpp` of Android `/system/bin/linker*` that loaded the `soinfo` of a library/executable had a `SOINFO_NAME_LEN=128` limit on the path/name passed to it before aae859cc, after which it was increased to `PATH_MAX`. Earlier, if path passed was `>= 128`, then `library name "<library_name>" too long` error would occur.

Before dcaef371, the `__linker_init_post_relocation()` function also passed `argv[0]` as executable path to `soinfo_alloc()` function to load its `soinfo`, instead of the actual absolute path of the executable. So before aae859cc, if either length was `>= 128`, then the process would abort with exit code `1`. Note that the `execve()` call itself will not fail, failure occurs before `main()` is called. The limit also applies to the interpreter defined in scripts, as interpreter is passed as `argv[0]` during execution.

Both fixes are only available in Android `>= 6`. For earlier versions like Android 5, the path for executables and libraries must be kept below the limit. However, for executables, to allow execution, the `argv[0]` can be shortened even if executable path is longer, or by first changing current working directory to executable's parent directory and then executing it with a relative path.

See also `TERMUX__PREFIX_DIR___MAX_LEN`, `TERMUX__PREFIX__BIN_FILE___SAFE_MAX_LEN`, `FILE_HEADER__BINPRM_BUF_SIZE` and `TERMUX__FILE_HEADER__BUFFER_SIZE`.

```
LD_DEBUG=3 /data/data/com.termux/files/usr/libexec/installed-tests/termux-exec/lib/termux-exec_nos_c_tre/scripts/termux/api/termux_exec/ld_preload/direct/exec/files/print-args-binary arg1; echo $?
1

linker W  [ android linker & debugger ]
linker D  DEBUG: library name "/data/data/com.termux/files/usr/libexec/installed-tests/termux-exec/lib/termux-exec_nos_c_tre/scripts/termux/api/termux_exec/ld_preload/direct/exec/files/print-args-binary" too long
```

```
(exec -a print-args-binary /data/data/com.termux/files/usr/libexec/installed-tests/termux-exec/lib/termux-exec_nos_c_tre/scripts/termux/api/termux_exec/ld_preload/direct/exec/files/print-args-binary arg1); echo $?
arg1
0
```

```
(cd /data/data/com.termux/files/usr/libexec/installed-tests/termux-exec/lib/termux-exec_nos_c_tre/scripts/termux/api/termux_exec/ld_preload/direct/exec/files && ./print-args-binary arg1); echo $?
arg1
0
```

- https://cs.android.com/android/_/android/platform/bionic/+/dcaef371
- https://cs.android.com/android/_/android/platform/bionic/+/aae859cc
- https://github.com/termux/termux-app/issues/213

Credits to @Grimler91 for finding that it was path length that was causing execution failure for binaries.

diff --git a/lib/termux-exec_nos_c_tre/tests/libtermux-exec_nos_c_tre_tests.in b/lib/termux-exec_nos_c_tre/tests/libtermux-exec_nos_c_tre_tests.in
--- a/lib/termux-exec_nos_c_tre/tests/libtermux-exec_nos_c_tre_tests.in
+++ b/lib/termux-exec_nos_c_tre/tests/libtermux-exec_nos_c_tre_tests.in
@@ -70,11 +70,16 @@ libtermux_exec__nos__c__unit_binary_tests__run_command() {
     termux_exec__tests__log 1 "Running 'libtermux-exec_nos_c_tre_${unit_binary_tests_variant}'"
 
     output="$(
+        # cd first and execute with relative path to shorten `argv[0]`,
+        # otherwise command will fail with exit code `1` on Android `< 6`
+        # without any error if `argv[0]` length is `>= 128`.
+        # Check `checkExecArg0BufferOverflow()` function in `ExecIntercept.h`.
+        cd "$TERMUX_EXEC__TESTS__TESTS_PATH/lib/termux-exec_nos_c_tre/bin" || exit $?
         printf -v "$TERMUX_EXEC__TESTS__LOG_LEVEL___N" "%s" "$TERMUX_EXEC__TESTS__LOG_LEVEL" || exit $?
         export "${TERMUX_EXEC__TESTS__LOG_LEVEL___N?}" || exit $?
         export LD_PRELOAD="$TERMUX_EXEC__TESTS__PRIMARY_LD_PRELOAD_FILE_PATH" || exit $?
         ASAN_OPTIONS="fast_unwind_on_malloc=false:detect_leaks=$TERMUX_EXEC__TESTS__DETECT_LEAKS" LSAN_OPTIONS="report_objects=$TERMUX_EXEC__TESTS__DETECT_LEAKS" \
-            "$TERMUX_EXEC__TESTS__TESTS_PATH/lib/termux-exec_nos_c_tre/bin/libtermux-exec_nos_c_tre_${unit_binary_tests_variant}" 2>&1)"
+            "./libtermux-exec_nos_c_tre_${unit_binary_tests_variant}" 2>&1)"
     return_value=$?
     if [ $return_value -eq 0 ] ||
         { [ $return_value -eq 141 ] &&
@@ -144,10 +149,15 @@ libtermux_exec__nos__c__runtime_binary_tests__run_command() {
 
     termux_exec__tests__log 1 "Running 'libtermux-exec_nos_c_tre_${runtime_binary_tests_variant}'"
     (
+        # cd first and execute with relative path to shorten `argv[0]`,
+        # otherwise command will fail with exit code `1` on Android `< 6`
+        # without any error if `argv[0]` length is `>= 128`.
+        # Check `checkExecArg0BufferOverflow()` function in `ExecIntercept.h`.
+        cd "$TERMUX_EXEC__TESTS__TESTS_PATH/lib/termux-exec_nos_c_tre/bin" || exit $?
         printf -v "$TERMUX_EXEC__TESTS__LOG_LEVEL___N" "%s" "$TERMUX_EXEC__TESTS__LOG_LEVEL" || exit $?
         export "${TERMUX_EXEC__TESTS__LOG_LEVEL___N?}" || exit $?
         ASAN_OPTIONS="fast_unwind_on_malloc=false:detect_leaks=$TERMUX_EXEC__TESTS__DETECT_LEAKS" LSAN_OPTIONS="report_objects=$TERMUX_EXEC__TESTS__DETECT_LEAKS" \
-            "$TERMUX_EXEC__TESTS__TESTS_PATH/lib/termux-exec_nos_c_tre/bin/libtermux-exec_nos_c_tre_${runtime_binary_tests_variant}"
+            "./libtermux-exec_nos_c_tre_${runtime_binary_tests_variant}"
     )
     return_value=$?
     if [ $return_value -ne 0 ]; then
